#!/usr/bin/env bash

sudo apt-get update -y
sudo apt-get install -y ufw

# Reset UFW to default to clear old rules
sudo ufw --force reset

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow required ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW firewall (without stopping it afterwards)
sudo ufw --force enable
