#!/usr/bin/env bash
# shellcheck disable=SC2154

# Update package list and install nginx
apt-get update -y
apt-get install -y nginx

# Get the hostname
hostname=$(hostname)

# Add the custom header to the default nginx site config
config_file="/etc/nginx/sites-available/default"
if ! grep -q "X-Served-By" "$config_file"; then
    # Add inside the server block
    sed -i "/server_name _;/a \\\tadd_header X-Served-By \$hostname;" "$config_file"
fi

# Restart Nginx using 'service'
sudo service nginx restart
