#!/usr/bin/env bash

# automate config mismatch error in nginx

rm /etc/nginx/sites-enabled/default

cd /etc/nginx/sites-enabled

ln -s ../sites-available/default .

service nginx restart

curl 0:80

