#!/usr/bin/env bash
# This script installs the Nginx and configure it to serve a html file

# install nginx
apt-get update
apt-get install nginx -y

# Check if installation was successful
nginx -v
if [ $? -ne 0 ]; then
    echo "Nginx installation failed."
    exit 1
fi

# Create a simple HTML file
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
service nginx restart
