#!/usr/bin/env bash
# Configures a new Ubuntu machine to serve a 301 redirect on /redirect_me

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Create index file
echo "Holberton School for the win!" > /var/www/html/index.html

# Insert 301 redirect in Nginx config
# The block is inserted directly under the first server block
sed -i '/^\s*server {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
service nginx restart
